spring:
  config:
    activate:
      on-profile: test

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,metrics,env,beans
  endpoint:
    health:
      show-details: always
