spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: when_authorized
