spring:
  application:
    name: playground

server:
  port: 8080

logging:
  level:
    root: INFO
    com.chenbitao.word.playground: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
